# Introduction

This book serves as an example of a machine learning (ML) based workflow
to use earth observation predictors
to quantify vegetation stress.

It serves mainly as an exercise in the framework for 
[AGDS2](https://geco-bern.github.io/agds2_course/).

In the example we use the fractional Light Use Efficiency (fLUE) as a proxy for 
vegetation stress. It describes reductions in the light use efficiency of plants. 
The fLUE data were derived from measurements from eddy covariance sites from the 
Fluxnet network.

Our goal is to build a model that predicts the fractional Light Use Efficiency 
(fLUE) using predictors that are widely available through satellite remote 
sensing or climate reanalysis (ERA5Land) data sets.

This book **requires prior knowledge** of programming in **R**, **git** and cloud 
based collaborative tools such as **Github**. 
The target group are students of the course Applied Geodata Science II (AGDS II) 
at the University of Bern, Switzerland.
The necessary prior knowledge covered by the courses AGDS I and II. Many of 
these concepts are described in the accompanying, free online book 
[AGDS](https://geco-bern.github.io/agds_book/).
